### ISSUE TITLE
[EMF resource] Add option to customise the Jena reasoner used during loading

### ISSUE THREAD

**Issue by agarciadom** [epsilonlabs/emf-rdf#21]
The option could look like this:

```yaml
dataModels:
  - data.ttl
schemaModels:
  - schema.ttl
reasoner: <identifer>
```
